const colombianCities = [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Soledad",
    "Bucaramanga",
    "Pereira",
    "Ibagué",
    "Villavicencio",
    "Bello",
    "Santa Marta",
    "Valledupar",
    "Montería",
    "Pasto",
    "Manizales",
    "Neiva",
    "Armenia",
    "Popayán",
    "Sincelejo",
    "Buenaventura",
    "Barrancabermeja",
    "Tunja",
    "Ríohacha",
    "Tuluá",
    "Florencia",
    "Cartago",
    "Ciénaga",
    "Quibdó",
    "Girardot",
    "Sogamoso",
    "Ipiales",
    "Duitama",
    "Magangué",
    "Arauca",
    "Tumaco",
    "Ocaña",
    "San Andrés",
    "Villa del Rosario",
    "San José del Guaviare",
    "Sabanalarga",
    "Yopal",
    "El Carmen de Bolivar",
    "Garzón",
    "El Banco",
    "Chiquinquirá",
    "Pamplona",
    "Lorica",
    "Turbo",
    "Arjona",
    "Honda",
    "Yarumal",
    "Puerto Berrío",
    "Túquerres",
    "Leticia",
    "Tame",
    "Mitú",
    "Santiago de Tolú",
    "Socorro",
    "Ayapel",
    "Campoalegre",
    "Mocoa",
    "San Jacinto",
    "Sonsón",
    "Puerto Carreño",
    "Puerto López",
    "San Martín",
    "Guapí",
    "Inírida",
    "Puerto Nariño",
    "Orocué",
    "Nuquí",
    "Juradó",
    "San Vicente del Caguán",
    "Guatapé",
    "Itaguí",
    "Envigado",
    "Sabaneta",
    "Soacha",
    "Floridablanca",
    "Dosquebradas",
    "Chía",
    "La Estrella",
    "Mosquera",
    "Malambo",
    "Funza",
    "Cajicá",
    "Copacabana",
    "La Virginia",
    "Facatativá",
    "Madrid",
    "Fusagasugá",
    "Los Patios",
    "Zipaquirá",
    "Girardota",
    "Tocancipá",
    "Caldas",
    "Rionegro",
    "Barbosa",
    "San José",
    "Galapa",
    "Cota",
    "Yumbo",
    "Alcalá",
    "La tebaida",
    "Baranoa",
    "Tabio",
    "Marinilla",
    "Turbaco",
    "Chinchiná",
    "Gachancipá",
    "Puerto Colombia",
    "La Ceja",
    "Girón",
    "Santuario",
    "Puerto Tejada",
    "Villa de San Diego",
    "Amagá",
    "Espinal",
    "Cereté",
    "Sibaté",
    "Sesquillé",
    "Santo Tomás",
    "Flandes",
    "Palmar de Varela",
    "Piedecuesta",
    "Nobsa",
    "San Gil",
    "Málaga",
    "La Unión",
    "Circasia",
    "San Bernardo",
    "Palmira",
    "Sopó",
    "Providencia",
    "Coveñas",
    "Montenegro",
    "Ponedera",
    "Pinillos",
    "Candelaria",
    "Apartadó",
    "Guarne",
    "Guateque",
    "Piendamó",
    "Jamundí",
    "Miranda",
    "San Andrés de Sotavento",
    "Tuchín",
    "Sandoná",
    "Quimbaya",
    "Sahagún",
    "Marmato",
    "Barbosa",
    "Corozal",
    "Suan",
    "Santa Isabel",
    "Cisneros",
    "La Mesa"
];

export default colombianCities;